-- MySQL Script generated by MySQL Workbench
-- Sat Apr  9 13:10:15 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
        'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bootcamp_dio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bootcamp_dio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bootcamp_dio` DEFAULT CHARACTER SET utf8;
USE `bootcamp_dio`;

-- -----------------------------------------------------
-- Table `bootcamp_dio`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bootcamp_dio`.`cursos`
(
    `pk_cod_curso` INT          NOT NULL AUTO_INCREMENT,
    `nome`         VARCHAR(45)  NOT NULL,
    `descricao`    VARCHAR(100) NOT NULL,
    `cargaHoraria` INT          NOT NULL,
    PRIMARY KEY (`pk_cod_curso`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bootcamp_dio`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bootcamp_dio`.`cursos`
(
    `pk_cod_curso` INT          NOT NULL AUTO_INCREMENT,
    `nome`         VARCHAR(45)  NOT NULL,
    `descricao`    VARCHAR(100) NOT NULL,
    `cargaHoraria` INT          NOT NULL,
    PRIMARY KEY (`pk_cod_curso`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bootcamp_dio`.`mentorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bootcamp_dio`.`mentorias`
(
    `pk_cod_mentoria` INT          NOT NULL AUTO_INCREMENT,
    `nome`            VARCHAR(45)  NOT NULL,
    `descricao`       VARCHAR(100) NOT NULL,
    `data`            VARCHAR(45)  NOT NULL,
    PRIMARY KEY (`pk_cod_mentoria`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bootcamp_dio`.`devs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bootcamp_dio`.`devs`
(
    `pk_cod_dev` INT         NOT NULL AUTO_INCREMENT,
    `nome`       VARCHAR(45) NOT NULL,
    PRIMARY KEY (`pk_cod_dev`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bootcamp_dio`.`bootcamps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bootcamp_dio`.`bootcamps`
(
    `pk_cod_bootcamp` INT          NOT NULL AUTO_INCREMENT,
    `nome`            VARCHAR(45)  NOT NULL,
    `descricao`       VARCHAR(100) NOT NULL,
    `dataInicial`     VARCHAR(45)  NOT NULL,
    `dataFinal`       VARCHAR(45)  NOT NULL,
    PRIMARY KEY (`pk_cod_bootcamp`)
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bootcamp_dio`.`devs_has_bootcamps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bootcamp_dio`.`devs_has_bootcamps`
(
    `fk_cod_dev`      INT     NOT NULL,
    `fk_cod_bootcamp` INT     NOT NULL,
    `concluido`       TINYINT NULL,
    INDEX `fk_devs_has_bootcamps_bootcamps1_idx` (`fk_cod_bootcamp` ASC) VISIBLE,
    INDEX `fk_devs_has_bootcamps_devs_idx` (`fk_cod_dev` ASC) VISIBLE,
    CONSTRAINT `fk_devs_has_bootcamps_devs`
        FOREIGN KEY (`fk_cod_dev`)
            REFERENCES `bootcamp_dio`.`devs` (`pk_cod_dev`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_devs_has_bootcamps_bootcamps1`
        FOREIGN KEY (`fk_cod_bootcamp`)
            REFERENCES `bootcamp_dio`.`bootcamps` (`pk_cod_bootcamp`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bootcamp_dio`.`bootcamps_has_mentorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bootcamp_dio`.`bootcamps_has_mentorias`
(
    `fk_cod_bootcamp` INT NOT NULL,
    `fk_cod_mentoria` INT NOT NULL,
    INDEX `fk_bootcamps_has_mentorias_mentorias1_idx` (`fk_cod_mentoria` ASC) VISIBLE,
    INDEX `fk_bootcamps_has_mentorias_bootcamps1_idx` (`fk_cod_bootcamp` ASC) VISIBLE,
    CONSTRAINT `fk_bootcamps_has_mentorias_bootcamps1`
        FOREIGN KEY (`fk_cod_bootcamp`)
            REFERENCES `bootcamp_dio`.`bootcamps` (`pk_cod_bootcamp`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_bootcamps_has_mentorias_mentorias1`
        FOREIGN KEY (`fk_cod_mentoria`)
            REFERENCES `bootcamp_dio`.`mentorias` (`pk_cod_mentoria`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bootcamp_dio`.`bootcamps_has_cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bootcamp_dio`.`bootcamps_has_cursos`
(
    `fk_cod_bootcamp` INT NOT NULL,
    `fk_cod_curso`    INT NOT NULL,
    INDEX `fk_bootcamps_has_cursos_cursos1_idx` (`fk_cod_curso` ASC) VISIBLE,
    INDEX `fk_bootcamps_has_cursos_bootcamps1_idx` (`fk_cod_bootcamp` ASC) VISIBLE,
    CONSTRAINT `fk_bootcamps_has_cursos_bootcamps1`
        FOREIGN KEY (`fk_cod_bootcamp`)
            REFERENCES `bootcamp_dio`.`bootcamps` (`pk_cod_bootcamp`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_bootcamps_has_cursos_cursos1`
        FOREIGN KEY (`fk_cod_curso`)
            REFERENCES `bootcamp_dio`.`cursos` (`pk_cod_curso`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bootcamp_dio`.`devs_has_cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bootcamp_dio`.`devs_has_cursos`
(
    `fk_cod_dev`   INT     NOT NULL,
    `fk_cod_curso` INT     NOT NULL,
    `concluido`    TINYINT NULL,
    INDEX `fk_devs_has_cursos_cursos1_idx` (`fk_cod_curso` ASC) VISIBLE,
    INDEX `fk_devs_has_cursos_devs1_idx` (`fk_cod_dev` ASC) VISIBLE,
    CONSTRAINT `fk_devs_has_cursos_devs1`
        FOREIGN KEY (`fk_cod_dev`)
            REFERENCES `bootcamp_dio`.`devs` (`pk_cod_dev`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_devs_has_cursos_cursos1`
        FOREIGN KEY (`fk_cod_curso`)
            REFERENCES `bootcamp_dio`.`cursos` (`pk_cod_curso`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bootcamp_dio`.`devs_has_mentorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bootcamp_dio`.`devs_has_mentorias`
(
    `fk_cod_dev`      INT     NOT NULL,
    `fk_cod_mentoria` INT     NOT NULL,
    `concluido`       TINYINT NULL,
    INDEX `fk_devs_has_mentorias_mentorias1_idx` (`fk_cod_mentoria` ASC) VISIBLE,
    INDEX `fk_devs_has_mentorias_devs1_idx` (`fk_cod_dev` ASC) VISIBLE,
    CONSTRAINT `fk_devs_has_mentorias_devs1`
        FOREIGN KEY (`fk_cod_dev`)
            REFERENCES `bootcamp_dio`.`devs` (`pk_cod_dev`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION,
    CONSTRAINT `fk_devs_has_mentorias_mentorias1`
        FOREIGN KEY (`fk_cod_mentoria`)
            REFERENCES `bootcamp_dio`.`mentorias` (`pk_cod_mentoria`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION
)
    ENGINE = InnoDB;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
