#Books
insert into books (author, title, description, price) values (1, "Harry Potter and the Philosopher Stone", "The boy wizard Harry Potter has been casting a spell over young readers and their families ever since 1997. Now the first book in this unmissable series celebrates 25 years in print! The paperback edition of the tale that introduced us to Harry, Ron and Hermione has been updated and dressed in silver to mark the occasion. It's time to take the magical journey of a lifetime.

Harry Potter has never even heard of Hogwarts when the letters start dropping on the doormat at number four, Privet Drive. Addressed in green ink on yellowish parchment with a purple seal, they are swiftly confiscated by his grisly aunt and uncle. Then, on Harry's eleventh birthday, a great beetle-eyed giant of a man called Rubeus Hagrid bursts in with some astonishing news: Harry Potter is a wizard, and he has a place at Hogwarts School of Witchcraft and Wizardry. An incredible adventure is about to begin!

These editions of the classic and internationally bestselling Harry Potter series feature thrilling jacket artwork by award-winning illustrator Jonny Duddle. They are the perfect starting point for anyone who's ready to lose themselves in the greatest children's story of all time. Available for one year only, Harry's first adventure - Harry Potter and the Philosopher's Stone - has been emblazoned in silver and refreshed with extra content including a new Hogwarts crest illustration and Q&A with Jonny Duddle, plus fun facts exploring the origins of names such as Albus Dumbledore, Hedwig and other favourite characters.", 56.23);

insert into books (author, title, description, price) values (2, "Cormoran Strike - The Cuckoo's Calling","A brilliant debut mystery in a classic vein: Detective Cormoran Strike investigates a supermodel's suicide.</em>

After losing his leg to a land mine in Afghanistan, Cormoran Strike is barely scraping by as a private investigator. Strike is down to one client, and creditors are calling. He has also just broken up with his longtime girlfriend and is living in his office.

Then John Bristow walks through his door with an amazing story: His sister, thelegendary supermodel Lula Landry, known to her friends as the Cuckoo, famously fell to her death a few months earlier. The police ruled it a suicide, but John refuses to believe that. The case plunges Strike into the world of multimillionaire beauties, rock-star boyfriends, and desperate designers, and it introduces him to every variety of pleasure, enticement, seduction, and delusion known to man.

You may think you know detectives, but you've never met one quite like Strike. You may think you know about the wealthy and famous, but you've never seen them under an investigation like this.

Introducing Cormoran Strike, this is the acclaimed first crime novel by J.K. Rowling, writing under the pseudonym Robert Galbraith.", 71.16);

insert into books (author, title, description, price) values (3, "Hunger Games - The Hunger Games", "Katniss is a 16-year-old girl living with her mother and younger sister in the poorest district of Panem, the remains of what used be the United States. Long ago the districts waged war on the Capitol and were defeated. As part of the surrender terms, each district agreed to send one boy and one girl to appear in an annual televised event called, 'The Hunger Games.' The terrain, rules, and level of audience participation may change but one thing is constant: kill or be killed. When Kat's sister is chosen by lottery, Kat steps up to go in her place. The first novel in the worldwide bestselling series by Suzanne Collins!Winning means fame and fortune. Losing means certain death. The Hunger Games have begun.... In the ruins of a place once known as North America lies the nation of Panem, a shining Capitol surrounded by twelve outlying districts. The Capitol is harsh and cruel and keeps the districts in line by forcing them all to send one boy and one girl between the ages of twelve and eighteen to participate in the annual Hunger Games, a fight to the death on live TV. Sixteen-year-old Katniss Everdeen regards it as a death sentence when she steps forward to take her sister's place in the Games. But Katniss has been close to dead before-and survival, for her, is second nature. Without really meaning to, she becomes a contender. But if she is to win, she will have to start making choices that weigh survival against humanity and life against love.", 71.16);

insert into books (author, title, description, price) values (1, "Harry Potter and the Chamber of Secrets", "'There is a plot, Harry Potter. A plot to make most terrible things happen at Hogwarts School of Witchcraft and Wizardry this year.'</em>

Harry Potter's summer has included the worst birthday ever, doomy warnings from a house-elf called Dobby, and rescue from the Dursleys by his friend Ron Weasley in a magical flying car! Back at Hogwarts School of Witchcraft and Wizardry for his second year, Harry hears strange whispers echo through empty corridors - and then the attacks start. Students are found as though turned to stone... Dobby's sinister predictions seem to be coming true.


Having become classics of our time, the Harry Potter eBooks never fail to bring comfort and escapism. With their message of hope, belonging and the enduring power of truth and love, the story of the Boy Who Lived continues to delight generations of new readers.", 60.12);

insert into books (author, title, description, price) values (2, "Cormoran Strike - The Silkworm", "<strong>Private investigator Cormoran Strike must track down a missing writer -- and a sinister killer bent on destruction -- in this 'wonderfully entertaining' mystery (Harlan Coben, New York Times Book Review) that inspired the acclaimed HBO Max series C.B. Strike.</strong>
  When novelist Owen Quine goes missing, his wife calls in private detective Cormoran Strike. At first, Mrs. Quine just thinks her husband has gone off by himself for a few days -- as he has done before -- and she wants Strike to find him and bring him home. But as Strike investigates, he discovers that Quine's disappearance is no coincidence. The novelist has just completed a manuscript featuring poisonous pen-portraits of almost everyone he knows. If the novel were published, it would ruin lives -- meaning that almost everyone in his life would have motives to silence him. When Quine is found brutally murdered under bizarre circumstances, Strike must race against time to understand the motivation of a ruthless killer, a killer unlike any he has encountered before . . . A compulsively readable crime novel with twists at every turn, The Silkworm is the second in J. K. Rowling's highly acclaimed series featuring Cormoran Strike and his determined young assistant, Robin Ellacott.", 60.99);

insert into books (author, title, description, price) values (3, "Hunger Games - Catching Fire", "Against all odds, Katniss Everdeen has won the annual Hunger Games with fellow district tribute Peeta Mellark. But it was a victory won by defiance of the Capitol and their harsh rules. Katniss and Peeta should be happy. After all, they have just won for themselves and their families a life of safety and plenty. But there are rumors of rebellion among the subjects, and Katniss and Peeta, to their horror, are the faces of that rebellion. The Capitol is angry. The Capitol wants revenge. Suzanne Collins continues the amazing story of Katniss Everdeen in the phenomenal Hunger Games trilogy.Against all odds, Katniss Everdeen has won the annual Hunger Games with fellow district tribute Peeta Mellark. But it was a victory won by defiance of the Capitol and their harsh rules. Katniss and Peeta should be happy. After all, they have just won for themselves and their families a life of safety and plenty. But there are rumors of rebellion among the subjects, and Katniss and Peeta, to their horror, are the faces of that rebellion. The Capitol is angry. The Capitol wants revenge.", 109.25);

insert into books (author, title, description, price) values (1, "Harry Potter and the Prisoner of Azkaban", "When the Knight Bus crashes through the darkness and screeches to a halt in front of him, it's the start of another far from ordinary year at Hogwarts for Harry Potter. Sirius Black, escaped mass-murderer and follower of Lord Voldemort, is on the run - and they say he is coming after Harry. In his first ever Divination class, Professor Trelawney sees an omen of death in Harry's tea leaves . But perhaps most terrifying of all are the Dementors patrolling the school grounds, with their soul-sucking kiss.

These new editions of the classic and internationally bestselling, multi-award-winning series feature instantly pick-up-able new jackets by Jonny Duddle, with huge child appeal, to bring Harry Potter to the next generation of readers. It's time to PASS THE MAGIC ON .", 68.00);

insert into books (author, title, description, price) values (2, "Cormoran Strike - Career of Evil","<strong>A disturbing package leads Detective Cormoran Strike and his assistant Robin Ellacott to investigate four dangerous murder suspects in this 'magnetic' British mystery (Michiko Kakutani, New York Times) that inspired the acclaimed HBO Max series C.B. Strike.</strong>    When Robin Ellacott opens an unexpected delivery, she is horrified to discover that it contains a woman's severed leg. Her boss, private detective Cormoran Strike, is less surprised but just as alarmed. He suspects that four people from his past could be responsible -- and any one of them is capable of sustained and unspeakable brutality. With the police focusing on the one suspect Strike has essentially ruled out, he and Robin take matters into their own hands and delve into the dark and twisted worlds of the other three men. But as more horrendous acts occur, time is running out for the two of them . . . Career of Evil is the third in J. K. Rowling's highly acclaimed series featuring private detective Cormoran Strike and his assistant Robin Ellacott. A fiendishly clever mystery with unexpected twists around every corner, Career of Evil is also a gripping story of a man and a woman at a crossroads in their personal and professional lives.", 69.80);

insert into books (author, title, description, price) values (3, "Hunger Games - Mockingjay", "Against all odds, Katniss Everdeen has survived the Hunger Games twice. But now that she's made it out of the bloody arena alive, she's still not safe. The Capitol is angry. The Capitol wants revenge. Who do they think should pay for the unrest? Katniss. And what's worse, President Snow has made it clear that no one else is safe either. Not Katniss's family, not her friends, not the people of District 12. Powerful and haunting, this thrilling final installment of Suzanne Collins's groundbreaking The Hunger Games trilogy promises to be one of the most talked about books of the year.", 64.70);

insert into books (author, title, description, price) values (1, "Harry Potter and the Goblet of Fire", "'There will be three tasks, spaced throughout the school year, and they will test the champions in many different ways ... their magical prowess - their daring - their powers of deduction - and, of course, their ability to cope with danger.'</em>

The Triwizard Tournament is to be held at Hogwarts. Only wizards who are over seventeen are allowed to enter - but that doesn't stop Harry dreaming that he will win the competition. Then at Hallowe'en, when the Goblet of Fire makes its selection, Harry is amazed to find his name is one of those that the magical cup picks out. He will face death-defying tasks, dragons and Dark wizards, but with the help of his best friends, Ron and Hermione, he might just make it through - alive!


Having become classics of our time, the Harry Potter eBooks never fail to bring comfort and escapism. With their message of hope, belonging and the enduring power of truth and love, the story of the Boy Who Lived continues to delight generations of new readers.", 62.00);

insert into books (author, title, description, price) values (2, "Cormoran Strike - Lethal White", "<strong>An unsettling cold case investigation ensnares Cormoran Strike and his partner in a web of dangerous secrets in this #1 New York Times bestseller, the inspiration for HBO Max's acclaimed series C.B. Strike.</strong> 
 When a troubled young man named Billy asks Cormoran Strike to help him investigate a crime he witnessed as a child, the private eye is left deeply troubled. While Billy is obviously mentally distressed and cannot remember many concrete details, there is something sincere about him and his story. But before Strike can question him further, Billy bolts from his office in a panic.
 Trying to get to the bottom of Billy's story, Strike and Robin Ellacott -- once his assistant, now a partner in the agency -- set off on a twisting trail that leads them through the backstreets of London, into a secretive inner sanctum within Parliament, and to a beautiful but sinister manor house deep in the countryside. And during this labyrinthine investigation, Strike's own life is far from straightforward. His newfound fame as a private eye means he can no longer operate behind the scenes as he once did. Plus, his relationship with his former assistant is more fraught than it ever has been; Robin is now invaluable to Strike in the business, but their personal relationship is much, much trickier than that. The most epic Robert Galbraith novel yet, Lethal White is 'addictive, murderous fun' for British mystery lovers and crime fiction fans alike (Vox</em>).", 60.99);

insert into books (author, title, description, price) values (1, "Harry Potter and the Order of the Phoenix", "'You are sharing the Dark Lord's thoughts and emotions. The Headmaster thinks it inadvisable for this to continue. He wishes me to teach you how to close your mind to the Dark Lord.'

Dark times have come to Hogwarts. After the Dementors' attack on his cousin Dudley, Harry Potter knows that Voldemort will stop at nothing to find him. There are many who deny the Dark Lord's return, but Harry is not alone: a secret order gathers at Grimmauld Place to fight against the Dark forces. Harry must allow Professor Snape to teach him how to protect himself from Voldemort's savage assaults on his mind. But they are growing stronger by the day and Harry is running out of time...


Having become classics of our time, the Harry Potter eBooks never fail to bring comfort and escapism. With their message of hope, belonging and the enduring power of truth and love, the story of the Boy Who Lived continues to delight generations of new readers.", 65.20);

insert into books (author, title, description, price) values (2, "Cormoran Strike - Troubled Blood", "<strongIn the epic fifth installment in this “compulsively readable” (People) series, Galbraith’s “irresistible hero and heroine” (USA Today) take on the decades-old cold case of a missing doctor, one which may be their grisliest yet.</strong>

Private Detective Cormoran Strike is visiting his family in Cornwall when he is approached by a woman asking for help finding her mother, Margot Bamborough—who went missing in mysterious circumstances in 1974.
 
Strike has never tackled a cold case before, let alone one forty years old. But despite the slim chance of success, he is intrigued and takes it on; adding to the long list of cases that he and his partner in the agency, Robin Ellacott, are currently working on. And Robin herself is also juggling a messy divorce and unwanted male attention, as well as battling her own feelings about Strike.
 
As Strike and Robin investigate Margot’s disappearance, they come up against a fiendishly complex case with leads that include tarot cards, a psychopathic serial killer and witnesses who cannot all be trusted. And they learn that even cases decades old can prove to be deadly . . ." , 80.25);

insert into books (author, title, description, price) values (1, "Harry Potter and the Half-blood Prince", "There it was, hanging in the sky above the school: the blazing green skull with a serpent tongue, the mark Death Eaters left behind whenever they had entered a building... wherever they had murdered...</em>

When Dumbledore arrives at Privet Drive one summer night to collect Harry Potter, his wand hand is blackened and shrivelled, but he does not reveal why. Secrets and suspicion are spreading through the wizarding world, and Hogwarts itself is not safe. Harry is convinced that Malfoy bears the Dark Mark: there is a Death Eater amongst them. Harry will need powerful magic and true friends as he explores Voldemort's darkest secrets, and Dumbledore prepares him to face his destiny...


Having become classics of our time, the Harry Potter eBooks never fail to bring comfort and escapism. With their message of hope, belonging and the enduring power of truth and love, the story of the Boy Who Lived continues to delight generations of new readers.",  70.00);

insert into books (author, title, description, price) values (1, "Harry Potter and the Deathly Hallows", "'Give me Harry Potter,' said Voldemort's voice, 'and none shall be harmed. Give me Harry Potter, and I shall leave the school untouched. Give me Harry Potter, and you will be rewarded.'</em>

As he climbs into the sidecar of Hagrid's motorbike and takes to the skies, leaving Privet Drive for the last time, Harry Potter knows that Lord Voldemort and the Death Eaters are not far behind. The protective charm that has kept Harry safe until now is broken, but he cannot keep hiding. The Dark Lord is breathing fear into everything Harry loves and to stop him Harry will have to find and destroy the remaining Horcruxes. The final battle must begin - Harry must stand and face his enemy...


Having become classics of our time, the Harry Potter eBooks never fail to bring comfort and escapism. With their message of hope, belonging and the enduring power of truth and love, the story of the Boy Who Lived continues to delight generations of new readers.", 80.00);

insert into books (author, title, description, price) values (2, "Cormoran Strike - The ink Black Heart", "The latest installment in the highly acclaimed, internationally bestselling Strike series finds Cormoran and Robin ensnared in another winding, wicked case.", 144.64);


#Authors
insert into authors (name) values("J. K. Rowling");
insert into authors (name) values("Robert Galbraith");
insert into authors (name) values("Suzanne Collins");
